routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Customer
Route::get('/customer', 'CustomerController@index')->name('customer')->middleware('auth');
Route::get('/customer/create', 'CustomerController@create')->middleware('auth');
Route::post('/customer/create','CustomerController@store')->middleware('auth');
Route::get('/customer/search','CustomerController@search')->name('customer_search')->middleware('auth');
Route::get('/customer/autocomplete','CustomerController@autocomplete')->name('customer_autocomplete')->middleware('auth');
Route::get('/customer/view/{id}', 'CustomerController@view')->middleware('auth')->name('customer.view');
Route::get('/customer/main_search','CustomerController@main_search')->name('customer_main_search')->middleware('auth');
Route::get('/customer/state_autocomplete','CustomerController@state_autocomplete')->name('state_autocomplete')->middleware('auth');

Route::get('/customer/edit/{id}', 'CustomerController@edit')->name('customer_edit')->middleware('auth');
Route::post('/customer/update/{id}', 'CustomerController@update')->name('customer_update')->middleware('auth');
Route::post('/customer/delete/{id}', 'CustomerController@delete')->name('customer_delete')->middleware('auth');

Route::get('/customer/filter_machine_status','CustomerController@filterMachineStatus')->name('filterMachineStatus')->middleware('auth');


// Contact
Route::get('/contact', 'ContactController@index')->name('contact')->middleware('auth');
Route::get('/contact/create', 'ContactController@create')->middleware('auth');
Route::post('/contact/create','ContactController@store')->middleware('auth');

Route::get('/contact/edit/{id}', 'ContactController@edit')->name('contact_edit')->middleware('auth');
Route::post('/contact/update/{id}', 'ContactController@update')->name('contact_update')->middleware('auth');
Route::post('/contact/delete/{id}', 'ContactController@delete')->name('contact_delete')->middleware('auth');

Route::get('/contact/search','ContactController@search')->name('contact_search')->middleware('auth');




Route::get('/', 'Auth\LoginController@loginview')->middleware('auth');
Auth::routes();

Route::get('/home', 'DashboardController@index')->name('home')->middleware('auth');

Route::get('/getGraphData', 'DashboardController@getGraphData')->name('getGraphData')->middleware('auth');
// User Controller
Route::resource('users', 'UserController')->middleware('auth');

// Machine Controller
Route::get('machines/all_machines', 'MachineController@autocomplete')->name('machine_autocomplete')->middleware('auth');
Route::get('machines/select_machine_num', 'MachineController@SelectMachineNum')->name('select_machine_num')->middleware('auth');
Route::get('/machines/search','MachineController@search')->name('machine_search')->middleware('auth');
Route::get('/machines/transfer_machine_autofill','MachineController@transferMachineAutofill')->name('transferMachineAutofill')->middleware('auth');
Route::get('/machines/duplicate_machine', 'MachineController@duplicateMachine')->name('duplicateMachine')->middleware('auth');
Route::resource('machines', 'MachineController')->middleware('auth');
// Route::get('/getGraphData', 'DashboardController@getGraphData')->name('getGraphData')->middleware('auth'); 
Route::get('/getCPAAdditionData', 'DashboardController@getCPAAdditionData')->name('getCPAAdditionData')->middleware('auth'); 
Route::get('/getBullhornSyncedData', 'DashboardController@getBullhornSyncedData')->name('getBullhornSyncedData')->middleware('auth'); 

Route::get('/getLogFilterData', 'DashboardController@getLogFilterData')->name('getLogFilterData')->middleware('auth'); 
// Technician Controller
Route::get('/technicians/autocomplete','TechnicianController@autocomplete')->name('technician_autocomplete')->middleware('auth');
Route::get('/technicians/search','TechnicianController@search')->name('technician_search')->middleware('auth');
Route::resource('technicians', 'TechnicianController')->middleware('auth');

// Log Controller
Route::get('/logs/get_history','LogController@get_history')->name('log_history')->middleware('auth');
Route::get('/logs/search','LogController@search')->name('log_search')->middleware('auth');
Route::resource('logs', 'LogController')->middleware('auth'); 
Route::get('/sources/searchwipe','ScriptController@searchwipe')->name('source_search_wipe')->middleware('auth');

// Source Controller
Route::get('/script/machine_source', 'ScriptController@machineSource')->name('machineSource')->middleware('auth');
Route::get('/script/autocomplete','ScriptController@autocomplete')->name('source_autocomplete')->middleware('auth');
Route::get('/script/autocompletewipe','ScriptController@autocompletewipe')->name('source_autocomplete_wipe')->middleware('auth');
Route::get('/script/search','ScriptController@search')->name('source_search')->middleware('auth');
Route::get('/script/search_source','ScriptController@search_source')->name('search_source')->middleware('auth');
Route::get('/script/pre_assign_source_search','ScriptController@preAssignSourceAutoComplete')->name('preAssignScriptearch')->middleware('auth');
Route::get('/script/transfer_source_auto_complete','ScriptController@transferSourceAutoComplete')->name('transferSourceAutoComplete')->middleware('auth');
Route::get('/script/pre_assign_source_auto_fill','ScriptController@preAssignSourceAutoFill')->name('preAssignSourceAutofill')->middleware('auth');
Route::get('/script/wipe_data_autofill','ScriptController@wipeDataAutoFill')->name('wipe_data_autofill')->middleware('auth');
Route::get('/script/logs','ScriptController@logs')->name('script.logs')->middleware('auth');
Route::get('/script/list','ScriptController@list')->name('script.list')->middleware('auth');
Route::resource('script', 'ScriptController')->middleware('auth');

Route::get('/contact/log_history/{id}','ContactController@getHistory')->middleware('auth')->name('contact.log_history');
Route::get('/contact/scriptrecord','ContactController@script_record')->name('contact.script_record')->middleware('auth');
Route::post('/contact/scriptrecord-paginate','ContactController@script_record_paginate')->name('contact.script_record_paginate')->middleware('auth');

// Route::get('/contact/scriptrecord-poplar','ContactController@getPoplarCampaigns')->name('contact.get_poplar_campaigns')->middleware('auth');
// Route::post('/contact/submit-scriptrecord-poplar','ContactController@sendPoplarPostcardCampaigns')->name('contact.submit_scriptrecord_poplar')->middleware('auth');

Route::group(['prefix' => 'poplar'], function(){
	Route::get('dump-poplar-campaign','PoplarController@dump_poplar_campaigns')->name('poplar.dump_poplar_campaigns'); //->middleware('auth');

	Route::get('scriptrecord-poplar','PoplarController@getPoplarCampaigns')->name('poplar.get_poplar_campaigns')->middleware('auth');
	Route::post('submit-scriptrecord-poplar','PoplarController@sendPoplarPostcardCampaigns')->name('poplar.submit_scriptrecord_poplar')->middleware('auth');

	/** Bullhorn IFrame Load */
	// Route::get('bullhorn/list-contact-campaigns/{bullhorn_id}','PoplarController@getListOfContactsByBullhornId')->name('poplar.bullhorn.list_contact_campaign');
	Route::get('bullhorn/list-contact-campaigns','PoplarController@getListOfContactsByBullhornId')->name('poplar.bullhorn.list_contact_campaign');
	Route::post('bullhorn/send-postcard-to-contact/{bullhorn_id}','PoplarController@sendPostcardToBUllhornContact')->name('poplar.bullhorn.send_postcard_contact');
});

Route::get('machines/log_history/{id}', 'MachineController@getHistory')->middleware('auth')->name('machine.log_history');
Route::get('/technicians/log_history/{id}','TechnicianController@getHistory')->middleware('auth')->name('technician.log_history');
Route::get('/script/log_history/{id}','ScriptController@getHistory')->middleware('auth');

Route::group(['prefix' => 'mailchimp'], function(){
	Route::get('listing/{page_number?}', 'MailchimpController@listing')->name('mailchimp.listing');
	Route::post('sync-data', 'MailchimpController@syncDataToBullhorn')->name('mailchimp.syncDataToBullhorn');
	Route::get('iframe-listing', 'MailchimpController@iframe_listing')->name('mailchimp.iframe_listing');
});

// Record Wipe Test Controller
Route::group(['middleware' => ['auth']], function () {
   	Route::get('/wipes/history','WipeController@history')->name('history');
   	Route::get('/wipes/wipes_search','WipeController@wipesSearch')->name('wipes_search');
	Route::get('/update-wipe','WipeController@updateWipe')->name('update-wipe');
	Route::get('/wipes/{id}/sendEmail','WipeController@sendEmail')->name('sendEmail');
	Route::get('/wipes/{id}/pdfView','WipeController@pdfView')->name('pdfView');
	Route::get('/wipes/discrepcod','WipeController@discrepcod')->name('discrepcod');
	Route::post('/wipes/storeMultiple','WipeController@storeMultiple')->name('wipes.storeMultiple');
	Route::get('/edit-RSO','WipeController@editRSO')->name('edit-RSO');
	Route::post('/update-RSO','WipeController@updateRSO')->name('update-RSO');
	Route::resource('wipes', 'WipeController');
});




// Pre-Assign Source Controller
Route::get('/preAssignSou/history','PreAssignScriptController@history')->name('prehistory')->middleware('auth');
Route::post('preAssignSou/createWipe', 'PreAssignScriptController@createWipe')->name('createWipe')->middleware('auth');
Route::post('preAssignSou/confirmShipDate', 'PreAssignScriptController@confirmShipDate')->name('confirmShipDate')->middleware('auth');
Route::get('/preAssignSou/search','PreAssignScriptController@search')->name('pre_assign_source_search')->middleware('auth');
Route::resource('preAssignSou', 'PreAssignScriptController')->middleware('auth');

app/Machine.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use DB;

class Machine extends Model
{
    use SoftDeletes;

    protected $table = 'machines';
    protected $fillable = [
        'mach_number', 'mach_model'
    ];

    public function ship_date(){
    	return $this->hasOne('App\MachLoc', 'machine_id', 'mach_number');
    }

    public function mach_loc(){
    	return $this->hasOne('App\MachLoc', 'machine_id', 'mach_number');
    }

    public function machloc(){
        return $this->hasMany('App\MachLoc', 'machine_id', 'mach_number');
    }

    public function wipedata(){
        return $this->hasOne('App\Wipe', 'mach_num', 'mach_number');
    }

    public function sourceloc_data(){
        return $this->hasMany('App\SourceLoc', 'mach_num', 'mach_number');
    }

    public static function getGbx($mach_num){

        $smod = DB::table('sourc_locs')
                        ->select('s_mod_num')
                        ->where('mach_num',$mach_num)
                        ->first();

        if(!isset($smod->s_mod_num)){
            return '';
        }

        $m_num = $smod->s_mod_num;      
        $gb =DB::table('smodlist')
                        ->select('gbx')
                        ->where('s_mod_num',$m_num)
                        ->first(); 

        return isset($gb->gbx)?$gb->gbx:'';
    }


}

resources/views/machine/history.blade.php
@extends('layout.app')

@section('content')

	<!-- Content -->
    <div class="content">
        <!-- Animated -->
        <div class="animated fadeIn">
        	<!--  Traffic  -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                        	
                        	<div class="row form-group">
                        		<div class="col-md-9">
                    				<h4 class="box-title"> Machine Tracker ({{ isset($machinedata->mach_number)?$machinedata->mach_number:''}})</h4>
                        		</div>

                        		<div class="col-md-3">
									<a href="{{ route('machines.index') }}" class="btn btn-outline-secondary float-right"><i class="fa fa-angle-double-left"></i> Back</a>
                        		</div>
                        	</div>
                        </div>
                        
                            @include('machine.history_table')


                        <div class="card-body"></div>
                    </div>
                </div><!-- /# column -->
            </div>
            <!--  /Traffic -->
            <div class="clearfix"></div>
        </div>
    	<!-- .animated -->
    </div>
    <!-- /.content -->
    <div class="clearfix"></div>

@endsection

resources/views/machine/index.blade.php
@extends('layout.app')

@section('content')

	<!-- Content -->
    <div class="content">
        <!-- Animated -->
        <div class="animated fadeIn">
        	<!--  Traffic  -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                        	<!-- Error & Message -->
	                        	@if (session()->has('insert'))
							      	<div class="alert alert-success alert-dismissible" role="alert">
							        	{{ session()->get('insert') }}
							        	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							          		<span aria-hidden="true">&times;</span>
							        	</button>
							      	</div>
							    @elseif (session()->has('update'))
							      	<div class="alert alert-info alert-dismissible" role="alert">
							        	{{ session()->get('update') }}
							        	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							          		<span aria-hidden="true">&times;</span>
							        	</button>
							      	</div>
							    @elseif (session()->has('delete'))
							      	<div class="alert alert-danger alert-dismissible" role="alert">
							        	{{ session()->get('delete') }}
							        	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							          		<span aria-hidden="true">&times;</span>
							        	</button>
							      	</div>
							    @endif
							<!-- Error & Message -->
                        	<div class="row form-group">
                        		<div class="col-md-9">
                    				<h4 class="box-title">Machine List </h4>
                        		</div>
                        		<div class="col-md-3">
                        			<a href="{{ route('machines.create') }}" class="btn btn-outline-success float-right"><i class="fa fa-plus"></i> ADD</a>
                        		</div>
                        	</div>   
							<div class="row form-group">

                        		<div class="col-md-6">
                        			<div class="input-group">
                        				<input class="form-control"  name="search_term" id="search_mach_term" placeholder="Search Machine Number, Machine Model">
                        				
                        			</div>
                        		</div>
                        		<div class="col-md-3">    
					             <div class="input-group">
					                <select class="form-control" name="status" id="status">
					                    <option selected disabled>Select Status</option>
					                    <option value="1">Active</option>
					                    <option value="0">Inactive</option>
					                </select>
					            </div>
					            </div>
					            <div class="col-md-3">    
					            <div class="input-group-btn">
                        					<button type="button" id="search_machine" class="btn btn-outline-primary" >Search</button>
                        				

                        				<a class="btn input-group-btn"href="{{ route('machines.index') }}" >Reset</a></div>
                        				
                        		</div>
                        	</div>
                        </div>
                        <div class="card-body nopadding">
                        	<div id="searchid" class="col-md-12 table-stats order-table ov-h nopadding">
	                            <table class="table">
				                  	<thead>
					                    <tr>
					                      <!-- <th>#</th> -->
					                      <th>Machine Number</th>
					                      <th>Machine Model</th>
					                      <th>Machine Status</th>
					                      <th>Source Number</th>
					                      <th>Source Model</th>
					                      <th>Ship Date</th>
					                      <th>Activity</th>
					                      <th>Status</th>
					                      <!-- <th>Updated At</th> -->
					                      <th>Action</th>
					                    </tr>
				                  	</thead>

				                  	<tbody class="table_format">
				                    	<!-- {{$i = 1}}  -->
				                    	@forelse($machines as $key => $machine) 				            
				                    	<?php
				                    	if($machine->wipedata){
				                    		$frequency = @$machine->wipedata->customer->wipetest_frequency;
				                    		$nextdate = date('d M Y', strtotime( "+".$frequency." months", strtotime($machine->wipedata['wipe_date'])));
				                    	} 
				                    	
				                    	?>
					                      	<tr>
						                       <!--  <td class="details-control" machine_num="{{ $machine->mach_number }}" machine_id="{{$machine->id}}">
						                        	<i class="fa fa-plus"></i>
						                        </td> --> 
												<td>
													<a class=""  rel="tooltip" title="View" href="{{ url('machines/log_history',$machine->id) }}">
														<u>{{$machine->mach_number}}</u>
													</a>
												</td>
						                        <!-- <td>{{ $machine->mach_number }}</td>  -->
						                        <td>{{ $machine->mach_model }}</td>
						                        <td>{{ $machine->mstats_desc }}</td> 
						                        <td> @forelse($machine->sourceloc_data as $k => $mach) {{ $mach->source_num }} @if( !$loop->last) , @endif @endforeach</td> 
						                        <td> @forelse($machine->sourceloc_data as $k => $mach) {{ $mach->s_mod_num }} @if( !$loop->last) , @endif @endforeach</td> 
						                        <td>
						                        	{{ ($machine->ship_date !== null) ? date('d M Y', strtotime($machine->ship_date)) : '' }} 
						                        </td> 
						                        <td>{{App\Machine::getGbx($machine->mach_number) }}</td>
						                        <td @if($machine->status == 1)class="text-success" @else class="text-danger" @endif>{{ $machine->status==1 ? 'Active' : 'Inactive' }}</td> 
						                        <!-- <td>{{ !empty($machine->updated_at)?date('d M Y', strtotime($machine->updated_at)):'-' }}</td> -->
												<td style="text-align: right; ">
						                        	<a href="{{ route('machines.edit', $machine->id) }}">
						                          		<i class="fa fa-edit edit_btn" rel="tooltip" title="Edit"></i>
						                          	</a>
						                        </td>
						                        <!-- <td style="padding-left:0px; text-align: left;">
						                        	<form action="{{ route('machines.destroy', $machine) }}" method="POST">
						                            	{{ csrf_field() }}
						                            	<input type="hidden" name="_method" value="DELETE">
						                            	<input type="hidden" name="_token" value="{{ csrf_token() }}">
						                            	<button type="submit" class="fabutton" onclick="return myFunction();">
						                              		<i class="fa fa-trash dlt_btn" rel="tooltip" title="Delete"></i>
						                            	</button>
						                          	</form>
						                        </td> -->
					                      	</tr>
				                    	@empty
					                        <tr>
					                          <td colspan="7" class="text-center">
					                          	<p>Machine Not Found.</p>
					                          </td> 
					                        </tr>
				                    	@endforelse
				                  	</tbody>
				                </table>
                        	</div> <!-- /.col-md-12 -->
				        </div><!-- card-body -->
                        <div class="card-body page_hide">
                            {{ $machines->onEachSide(1)->links() }}
                        </div>
                        <div class="card-body"></div>
                    </div>
                </div><!-- /# column -->
            </div>
            <!--  /Traffic -->
            <div class="clearfix"></div>
        </div>
    	<!-- .animated -->
    </div>
    <!-- /.content -->
    <div class="clearfix"></div>
<script>
	jQuery(document).ready(function() {

		jQuery('.details-control').on('click', function()
		{

			$td = jQuery(this).closest('td')
			$tr = jQuery(this).closest('tr')
			$this = jQuery(this)

			// jQuery('tbody').find('.details-control i').removeClass('fa-minus').addClass('fa-plus')
			jQuery('tbody').find('.show_data').remove();
			if($this.find('i').hasClass('fa-minus')){
			jQuery('tbody').find('.details-control i').removeClass('fa-minus').addClass('fa-plus')
				$this.find('i').removeClass('fa-minus').addClass('fa-plus')
			}else{
			jQuery('tbody').find('.details-control i').removeClass('fa-minus').addClass('fa-plus')
				$this.find('i').removeClass('fa-plus').addClass('fa-minus')

				var machine_id = $td.attr('machine_id');
				var machine_num = $td.attr('machine_num');

				console.log($td)
				// console.log(machine_id)
				console.log(machine_num)
				

				jQuery.ajax({
					url:"{{ route('machineSource') }}",
					method:'GET',
					data:{machine_id:machine_id, machine_num: machine_num},
					dataType:'json',
					success:function(data)
					{
						$tr.after(data.source_table_data);
						// jQuery('#machine_table tbody .show_data').last().after(data.source_table_data);
					}
				})

			}
		});
	} );
</script>


    <!-- Search Machine -->
        <script>
            jQuery(document).ready(function(){
                function fetch_machine_data(query,status,page)
                {
                    jQuery.ajax({
                        url:"{{ route('machine_search') }}",
                        method:'GET',
                        data:{query:query,status:status,page:page},
                        dataType:'html',
                        success:function(data)
                        {
                            jQuery('#searchid').html(data);
                            jQuery('.page_hide').css('cssText', 'display:none');
                            //searchData();
                        }
                    })
                }
                
	                jQuery(document).on('click', '#search_machine', function(){
	                    
	                    var query = jQuery('#search_mach_term').val();
	                    var status = jQuery('#status').val();
	                     if (query != ''|| null !=status) {

	                        fetch_machine_data(query,status,1);
	                    }
					 
					 });

	                jQuery(document).on('click', '.pagination a', function(event){
	                  

	                  var query = jQuery('#search_mach_term').val();
	                  var status = jQuery('#status').val();

	                     if (query != ''|| null !=status) {
	                     	event.preventDefault(); 
	                  var page = jQuery(this).attr('href').split('page=')[1];
	                  
	                     fetch_machine_data(query,status,page);

	                   }  
	                 });
                

            });

            jQuery('#search_mach_term').keypress(function (e) {
                var key = e.which;
                if(key == 13)  // the enter key code
                {
                    jQuery('#search_machine').click();
                    return false;  
                }
            });  

            function searchData(){
                jQuery('.details-control').on('click', function()
                {
                    $td = jQuery(this).closest('td')
                    $tr = jQuery(this).closest('tr')
                    $this = jQuery(this)

                    // jQuery('tbody').find('.details-control i').removeClass('fa-minus').addClass('fa-plus')
                    jQuery('tbody').find('.show_data').remove();
                    if($this.find('i').hasClass('fa-minus')){
                    jQuery('tbody').find('.details-control i').removeClass('fa-minus').addClass('fa-plus')
                        $this.find('i').removeClass('fa-minus').addClass('fa-plus')
                    }else{
                    jQuery('tbody').find('.details-control i').removeClass('fa-minus').addClass('fa-plus')
                        $this.find('i').removeClass('fa-plus').addClass('fa-minus')

                        var machine_id = $td.attr('machine_id');
                        var machine_num = $td.attr('machine_num');

                        console.log($td)
                        // console.log(machine_id)
                        console.log(machine_num)
                        

                        jQuery.ajax({
                            url:"{{ route('machineSource') }}",
                            method:'GET',
                            data:{machine_id:machine_id, machine_num: machine_num},
                            dataType:'json',
                            success:function(data)
                            {
                                $tr.after(data.source_table_data);
                                // jQuery('#machine_table tbody .show_data').last().after(data.source_table_data);
                            }
                        })

                    }
                });
            }
        </script>
    <!-- Search Machine -->
<style type="text/css">
	.show_data{
		background-color: aliceblue;
	}

	.show_data td{
		border: 0px !important;
		padding: 3px !important;
	}
</style>
@endsection

resources/views/machine/search.blade.php
<table class="table">
				                  	<thead>
					                    <tr>
					                      <!-- <th>#</th> -->
					                      <th>Machine Number</th>
					                      <th>Machine Model</th>
					                      <th>Machine Status</th>
					                      <th>Source Number</th>
					                      <th>Source Model</th>
					                      <th>Ship Date</th>
					                      <th>Activity</th>
					                      <th>Status</th>
					                      <th>Action</th>
					                    </tr>
				                  	</thead>
				                  	
				                  	<tbody class="table_format">
				                    	<!-- {{$i = 1}}  -->
				                    	<?php if(count($machines) >0){ ?>	
				                    	@forelse($machines as $key => $machine) 				            
				                    	<?php
				                    	if($machine->wipedata){
				                    		$frequency = @$machine->wipedata->customer->wipetest_frequency;
				                    		$nextdate = date('d M Y', strtotime( "+".$frequency." months", strtotime($machine->wipedata['wipe_date'])));
				                    	} 
				                    	
				                    	?>
					                      	<tr>
						                       <!--  <td class="details-control" machine_num="{{ $machine->mach_number }}" machine_id="{{$machine->id}}">
						                        	<i class="fa fa-plus"></i>
						                        </td> --> 
												<td>
													<a class=""  rel="tooltip" title="View" href="{{ url('machines/log_history',$machine->id) }}">
														<u>{{$machine->mach_number}}</u>
													</a>
												</td>
						                        <!-- <td>{{ $machine->mach_number }}</td>  -->
						                        <td>{{ $machine->mach_model }}</td>
						                        <td>{{ $machine->mstats_desc }}</td>  
						                        <td> @forelse($machine->sourceloc_data as $k => $mach) {{ $mach->source_num }} @if( !$loop->last) , @endif @endforeach</td> 
						                        <td> @forelse($machine->sourceloc_data as $k => $mach) {{ $mach->s_mod_num }} @if( !$loop->last) , @endif @endforeach</td> 
						                        <td>
						                        	{{ ($machine->ship_date !== null) ? date('d M Y', strtotime($machine->ship_date)) : '' }} 
						                        </td> 
						                        <td>{{App\Machine::getGbx($machine->mach_number) }}</td>
						                        <td @if($machine->status == 1)class="text-success" @else class="text-danger" @endif>{{ $machine->status==1 ? 'Active' : 'Inactive' }}</td> 
						                        <td style="text-align: right; ">
						                        	<a href="{{ route('machines.edit', $machine) }}">
						                          		<i class="fa fa-edit edit_btn" rel="tooltip" title="Edit"></i>
						                          	</a>
						                        </td>
						                        <!-- <td style="padding-left:0px; text-align: left;">
						                        	<form action="{{ route('machines.destroy', $machine) }}" method="POST">
						                            	{{ csrf_field() }}
						                            	<input type="hidden" name="_method" value="DELETE">
						                            	<input type="hidden" name="_token" value="{{ csrf_token() }}">
						                            	<button type="submit" class="fabutton" onclick="return myFunction();">
						                              		<i class="fa fa-trash dlt_btn" rel="tooltip" title="Delete"></i>
						                            	</button>
						                          	</form>
						                        </td> -->
					                      	</tr>
				                    	@empty
					                        <tr>
					                          <td colspan="7" class="text-center">
					                          	<p>Machine Not Found.</p>
					                          </td> 
					                        </tr>
				                    	@endforelse
				                    <?php }else{ ?>
				                    	<tr>
					                          <td colspan="7" class="text-center">
					                          	<p>Machine Not Found.</p>
					                          </td> 
					                        </tr>
					                    <?php } ?>
				                  	</tbody>
				                </table>
				                <div class="card-body">
                            {{ $machines->links() }}
                        </div>