routes/web.php
Route::post('/contact/update/{id}', 'ContactController@update')->name('contact_update')->middleware('auth');
Route::post('/contact/delete/{id}', 'ContactController@delete')->name('contact_delete')->middleware('auth');

Route::get('/contact/search','ContactController@search')->name('contact_search')->middleware('auth');




Route::get('/', 'Auth\LoginController@loginview')->middleware('auth');
Auth::routes();

Route::get('/home', 'DashboardController@index')->name('home')->middleware('auth');

Route::get('/getGraphData', 'DashboardController@getGraphData')->name('getGraphData')->middleware('auth');
// User Controller
Route::resource('users', 'UserController')->middleware('auth');

// Machine Controller
Route::get('machines/all_machines', 'MachineController@autocomplete')->name('machine_autocomplete')->middleware('auth');
Route::get('machines/select_machine_num', 'MachineController@SelectMachineNum')->name('select_machine_num')->middleware('auth');
Route::get('/machines/search','MachineController@search')->name('machine_search')->middleware('auth');
Route::get('/machines/transfer_machine_autofill','MachineController@transferMachineAutofill')->name('transferMachineAutofill')->middleware('auth');
Route::get('/machines/duplicate_machine', 'MachineController@duplicateMachine')->name('duplicateMachine')->middleware('auth');
Route::resource('machines', 'MachineController')->middleware('auth');
// Route::get('/getGraphData', 'DashboardController@getGraphData')->name('getGraphData')->middleware('auth'); 
Route::get('/getCPAAdditionData', 'DashboardController@getCPAAdditionData')->name('getCPAAdditionData')->middleware('auth'); 
Route::get('/getBullhornSyncedData', 'DashboardController@getBullhornSyncedData')->name('getBullhornSyncedData')->middleware('auth'); 

Route::get('/getLogFilterData', 'DashboardController@getLogFilterData')->name('getLogFilterData')->middleware('auth'); 
// Technician Controller
Route::get('/technicians/autocomplete','TechnicianController@autocomplete')->name('technician_autocomplete')->middleware('auth');
Route::get('/technicians/search','TechnicianController@search')->name('technician_search')->middleware('auth');
Route::resource('technicians', 'TechnicianController')->middleware('auth');

// Log Controller
Route::get('/logs/get_history','LogController@get_history')->name('log_history')->middleware('auth');
Route::get('/logs/search','LogController@search')->name('log_search')->middleware('auth');
Route::resource('logs', 'LogController')->middleware('auth'); 
Route::get('/sources/searchwipe','ScriptController@searchwipe')->name('source_search_wipe')->middleware('auth');

// Source Controller
Route::get('/script/machine_source', 'ScriptController@machineSource')->name('machineSource')->middleware('auth');
Route::get('/script/autocomplete','ScriptController@autocomplete')->name('source_autocomplete')->middleware('auth');
Route::get('/script/autocompletewipe','ScriptController@autocompletewipe')->name('source_autocomplete_wipe')->middleware('auth');
Route::get('/script/search','ScriptController@search')->name('source_search')->middleware('auth');
Route::get('/script/search_source','ScriptController@search_source')->name('search_source')->middleware('auth');
Route::get('/script/pre_assign_source_search','ScriptController@preAssignSourceAutoComplete')->name('preAssignScriptearch')->middleware('auth');
Route::get('/script/transfer_source_auto_complete','ScriptController@transferSourceAutoComplete')->name('transferSourceAutoComplete')->middleware('auth');
Route::get('/script/pre_assign_source_auto_fill','ScriptController@preAssignSourceAutoFill')->name('preAssignSourceAutofill')->middleware('auth');
Route::get('/script/wipe_data_autofill','ScriptController@wipeDataAutoFill')->name('wipe_data_autofill')->middleware('auth');
Route::get('/script/logs','ScriptController@logs')->name('script.logs')->middleware('auth');
Route::get('/script/list','ScriptController@list')->name('script.list')->middleware('auth');
Route::resource('script', 'ScriptController')->middleware('auth');

Route::get('/contact/log_history/{id}','ContactController@getHistory')->middleware('auth')->name('contact.log_history');
Route::get('/contact/scriptrecord','ContactController@script_record')->name('contact.script_record')->middleware('auth');
Route::post('/contact/scriptrecord-paginate','ContactController@script_record_paginate')->name('contact.script_record_paginate')->middleware('auth');

// Route::get('/contact/scriptrecord-poplar','ContactController@getPoplarCampaigns')->name('contact.get_poplar_campaigns')->middleware('auth');
// Route::post('/contact/submit-scriptrecord-poplar','ContactController@sendPoplarPostcardCampaigns')->name('contact.submit_scriptrecord_poplar')->middleware('auth');

Route::group(['prefix' => 'poplar'], function(){
	Route::get('dump-poplar-campaign','PoplarController@dump_poplar_campaigns')->name('poplar.dump_poplar_campaigns'); //->middleware('auth');

	Route::get('scriptrecord-poplar','PoplarController@getPoplarCampaigns')->name('poplar.get_poplar_campaigns')->middleware('auth');
	Route::post('submit-scriptrecord-poplar','PoplarController@sendPoplarPostcardCampaigns')->name('poplar.submit_scriptrecord_poplar')->middleware('auth');

	/** Bullhorn IFrame Load */
	// Route::get('bullhorn/list-contact-campaigns/{bullhorn_id}','PoplarController@getListOfContactsByBullhornId')->name('poplar.bullhorn.list_contact_campaign');
	Route::get('bullhorn/list-contact-campaigns','PoplarController@getListOfContactsByBullhornId')->name('poplar.bullhorn.list_contact_campaign');
	Route::post('bullhorn/send-postcard-to-contact/{bullhorn_id}','PoplarController@sendPostcardToBUllhornContact')->name('poplar.bullhorn.send_postcard_contact');
});

Route::get('machines/log_history/{id}', 'MachineController@getHistory')->middleware('auth')->name('machine.log_history');
Route::get('/technicians/log_history/{id}','TechnicianController@getHistory')->middleware('auth')->name('technician.log_history');
Route::get('/script/log_history/{id}','ScriptController@getHistory')->middleware('auth');

Route::group(['prefix' => 'mailchimp'], function(){
	Route::get('listing/{page_number?}', 'MailchimpController@listing')->name('mailchimp.listing');
	Route::post('sync-data', 'MailchimpController@syncDataToBullhorn')->name('mailchimp.syncDataToBullhorn');
	Route::get('iframe-listing', 'MailchimpController@iframe_listing')->name('mailchimp.iframe_listing');
});

// Record Wipe Test Controller
Route::group(['middleware' => ['auth']], function () {
   	Route::get('/wipes/history','WipeController@history')->name('history');
   	Route::get('/wipes/wipes_search','WipeController@wipesSearch')->name('wipes_search');
	Route::get('/update-wipe','WipeController@updateWipe')->name('update-wipe');
	Route::get('/wipes/{id}/sendEmail','WipeController@sendEmail')->name('sendEmail');
	Route::get('/wipes/{id}/pdfView','WipeController@pdfView')->name('pdfView');
	Route::get('/wipes/discrepcod','WipeController@discrepcod')->name('discrepcod');
	Route::post('/wipes/storeMultiple','WipeController@storeMultiple')->name('wipes.storeMultiple');
	Route::get('/edit-RSO','WipeController@editRSO')->name('edit-RSO');
	Route::post('/update-RSO','WipeController@updateRSO')->name('update-RSO');
	Route::resource('wipes', 'WipeController');
});




// Pre-Assign Source Controller
Route::get('/preAssignSou/history','PreAssignScriptController@history')->name('prehistory')->middleware('auth');
Route::post('preAssignSou/createWipe', 'PreAssignScriptController@createWipe')->name('createWipe')->middleware('auth');
Route::post('preAssignSou/confirmShipDate', 'PreAssignScriptController@confirmShipDate')->name('confirmShipDate')->middleware('auth');
Route::get('/preAssignSou/search','PreAssignScriptController@search')->name('pre_assign_source_search')->middleware('auth');
Route::resource('preAssignSou', 'PreAssignScriptController')->middleware('auth');

Route::get('update-source-log', 'PreAssignScriptController@updateSourceLog')->name('update-source-log')->middleware('auth');

// Transfer Source Controller
Route::resource('TransferSou', 'TransferScriptController')->middleware('auth');
Route::get('TransferSou/confirm/{id}', 'TransferScriptController@confirm')->name('TransferSou.confirm')->middleware('auth');
Route::post('update_confirmlog', 'TransferScriptController@updateconfirmlog')->name('update_confirmlog')->middleware('auth');
// Signature Upload Controller
Route::resource('signatures', 'SignatureUploadController')->middleware('auth');

// Document Upload Controller
Route::resource('upload_document', 'UploadDocumentController')->middleware('auth');
Route::post('document/upload', 'UploadDocumentController@documentUpload')->name('document.upload')->middleware('auth');
Route::get('/getTypeData', 'UploadDocumentController@getTypeData')->name('getTypeData')->middleware('auth'); 
Route::get('/contacts/transfer_contact_auto_complete','ContactController@transferContactAutoComplete')->name('transferContactAutoComplete')->middleware('auth');

// Regulatory Report Controller
Route::resource('regulatory_report', 'RegulatoryReportController')->middleware('auth');
Route::get('/get_quarterly_data','RegulatoryReportController@getQuarterlyData')->name('getQuarterlyData')->middleware('auth');
Route::get('view_pdf/{fromdate}/{todate}/{state}', 'RegulatoryReportController@viewQuarterlyPdf');
// customer report controller
Route::resource('customer_report', 'CustomerReportController')->middleware('auth');

//Regulatory agency
Route::resource('regulatory_agency', 'RegulatoryAgencyController')->middleware('auth');
Route::post('/regulatory_agency/store','RegulatoryAgencyController@store')->middleware('auth');
Route::post('/regulatory_agency/update/{id}','RegulatoryAgencyController@update')->middleware('auth');

Route::get('/source/log_history/{id}', 'ScriptController@getHistory')->name('source.log_history')->middleware('auth');


// Transfer Machine Controller

resources/views/transfer_source/index.blade.php
@extends('layout.app')

@section('content')
<style type="text/css">
        .confirmWipeTest{
            height: calc(1.25rem + 2px);
        }
    </style>

	<!-- Content -->
    <div class="content">
        <!-- Animated -->
        <div class="animated fadeIn">
        	<!--  Traffic  -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <!-- Error & Message -->
                                @if (session()->has('insert'))
                                    <div class="alert alert-success alert-dismissible" role="alert">
                                        {{ session()->get('insert') }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @elseif (session()->has('update'))
                                    <div class="alert alert-info alert-dismissible" role="alert">
                                        {{ session()->get('update') }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @elseif (session()->has('delete'))
                                    <div class="alert alert-danger alert-dismissible" role="alert">
                                        {{ session()->get('delete') }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                            <!-- Error & Message -->
                            <div class="row form-group">
                                <div class="col-md-3">
                                    <h4 class="box-title">Transfer Source List </h4>
                                </div>

                                <div class="col-md-6">
                                    <div class="input-group">
                                        <input class="form-control"  name="search_term" id="search_wipe_term" placeholder="Search..">
                                        <div class="input-group-btn">
                                            <button type="button" id="search_wipe" class="btn btn-outline-primary" >Search</button>
                                        </div>

                                        <a class="btn input-group-btn"href="{{ route('TransferSou.index') }}" >Reset</a>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <a href="{{ route('TransferSou.create') }}#idc" class="btn btn-outline-success float-right"><i class="fa fa-plus"></i> ADD</a>
                                </div>
                            </div>
                        </div>
                        <div class="card-body nopadding">
                            <div class="col-md-12 table-stats order-table ov-h nopadding">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <!-- <th>#</th> -->
                                            <th>Source Number</th>
                                            <th>Machine Number</th>
                                            <th>Source Model</th>
                                            <th>Source Status</th>
                                            <th>Ship Date</th>
                                            <!-- <th>Installation Date</th> -->
                                            <th>Confirm</th>
                                            <th colspan="2" style="text-align: left;">Action</th>
                                        </tr>
                                    </thead>

                                    <tbody class="table_format">
                                        @forelse($transfer_sources as $key => $transfer_source)
                                            <tr>
                                                <!-- <td>{{ $transfer_sources->firstItem() + $key }}</td>  -->
                                                <td>{{ $transfer_source->source_num }}</td> 
                                                <td>{{ $transfer_source->mach_num }}</td> 
                                                <td>{{ $transfer_source->s_mod_num }}</td> 
                                                <td>{{ $transfer_source->source_status->sstat_desc }}</td> 
                                                <td>{{ date('m/d/y', strtotime($transfer_source->s_ship_date)) }}</td> 
                                                <!-- <td>{{ ($transfer_source->inst_date=="")?'-':date('m/d/y', strtotime($transfer_source->inst_date))  }}</td> -->
                                                <td> 
                                                    <!-- <input type="checkbox" sourcelogid="{{ $transfer_source->id }}" source_num="{{ $transfer_source->source_num }}" mach_number="{{ $transfer_source->mach_num }}" name="confirm" class="form-control confirmWipeTest" id="confirmWipeTest">  -->
                                                    <a href="{{ route('TransferSou.confirm', $transfer_source) }}" class="btn btn-primary">
                                                        Confirm Source Returned
                                                    </a>
                                                </td>

                                                <td style="text-align: left; width: 5%;">
                                                    
                                                    <a href="{{ route('TransferSou.edit', $transfer_source) }}">
                                                       <i class="fa fa-edit edit_btn" rel="tooltip" title="Edit"></i>
                                                    </a>
                                                    
                                                </td>
                                                <td style="text-align: left;">
                                                    <form action="{{ route('TransferSou.destroy', $transfer_source) }}" method="POST">
                                                        {{ csrf_field() }}
                                                        <input type="hidden" name="_method" value="DELETE">
                                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                        <button type="submit" class="fabutton" onclick="return myFunction();">
                                                            <i class="fa fa-trash dlt_btn" rel="tooltip" title="Delete"></i>
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                              <td colspan="7" class="text-center">
                                                <p>Transfer Source Not Found.</p>
                                              </td> 
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div> <!-- /.col-md-12 -->
                        </div><!-- card-body -->
                        <div class="card-body">
                            {{ $transfer_sources->onEachSide(1)->links() }}
                        </div>
                        <div class="card-body"></div>
                    </div>
                </div><!-- /# column -->
            </div>
            <!--  /Traffic -->
            <div class="clearfix"></div>
        </div>
    	<!-- .animated -->
    </div>
    <!-- /.content -->
    <div class="clearfix"></div>

     <!-- ========================== Modal pop-up=====================-->
    <div class="modal fade" id="confirmWipe" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" style="background-color: darkgrey">
                    <h5 class="modal-title">Confirm Transfer source </h5>
                </div>
                <div class="modal-body">
                    <div class="row" style="padding-left: 15px;">
                        <h5> Are you sure, you want to update this transter source? </h5>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="confirmYes" class="btn btn-success">Yes</button>
                    <button type="button" id="confirmNo" class="btn btn-danger">No</button>
                </div>
            </div>      
        </div>
    </div>
    <input type="hidden" class="source_num">
    <input type="hidden" class="mach_num">
    <input type="hidden" class="sourcelogid">


    <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery('.confirmWipeTest').click(function(){
                jQuery('.source_num').val(jQuery(this).attr('source_num'));
                jQuery('.mach_num').val(jQuery(this).attr('mach_number'));
                jQuery('.sourcelogid').val(jQuery(this).attr('sourcelogid'));
                jQuery('#confirmWipe').modal({
                    backdrop: 'static',
                    keyboard: false
                });
                jQuery('#confirmWipe').modal('show');
            });

            jQuery('#confirmYes').click(function(){
                var sourcelog = jQuery('.sourcelogid').val();
                jQuery.ajax({
                    type: "GET",
                    dataType: "JSON",
                    data:{"sourceloc_id" : sourcelog},
                    url: "{{ route('update-source-log') }}",
                    success: function(data) {
                        location.reload();
                        //jQuery("tr[source-log="+sourcelog+"]").hide();
                        //jQuery('#confirmWipe').modal('hide');
                    },
                    error:function(error){
                        console.log('error');
                    }
                });
            });

            jQuery('#confirmNo').click(function(){
                var sourcelog = jQuery('.sourcelogid').val();
                jQuery("input[sourcelogid="+sourcelog+"]").prop("checked", false);
                jQuery('#confirmWipe').modal('hide');
            });
        });
    </script>

@endsection