routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Customer
Route::get('/customer', 'CustomerController@index')->name('customer')->middleware('auth');
Route::get('/customer/create', 'CustomerController@create')->middleware('auth');
Route::post('/customer/create','CustomerController@store')->middleware('auth');
Route::get('/customer/search','CustomerController@search')->name('customer_search')->middleware('auth');
Route::get('/customer/autocomplete','CustomerController@autocomplete')->name('customer_autocomplete')->middleware('auth');
Route::get('/customer/view/{id}', 'CustomerController@view')->middleware('auth')->name('customer.view');
Route::get('/customer/main_search','CustomerController@main_search')->name('customer_main_search')->middleware('auth');
Route::get('/customer/state_autocomplete','CustomerController@state_autocomplete')->name('state_autocomplete')->middleware('auth');

Route::get('/customer/edit/{id}', 'CustomerController@edit')->name('customer_edit')->middleware('auth');
Route::post('/customer/update/{id}', 'CustomerController@update')->name('customer_update')->middleware('auth');
Route::post('/customer/delete/{id}', 'CustomerController@delete')->name('customer_delete')->middleware('auth');

Route::get('/customer/filter_machine_status','CustomerController@filterMachineStatus')->name('filterMachineStatus')->middleware('auth');


// Contact
Route::get('/contact', 'ContactController@index')->name('contact')->middleware('auth');
Route::get('/contact/create', 'ContactController@create')->middleware('auth');
Route::post('/contact/create','ContactController@store')->middleware('auth');

Route::get('/contact/edit/{id}', 'ContactController@edit')->name('contact_edit')->middleware('auth');
Route::post('/contact/update/{id}', 'ContactController@update')->name('contact_update')->middleware('auth');
Route::post('/contact/delete/{id}', 'ContactController@delete')->name('contact_delete')->middleware('auth');

Route::get('/contact/search','ContactController@search')->name('contact_search')->middleware('auth');




Route::get('/', 'Auth\LoginController@loginview')->middleware('auth');
Auth::routes();

Route::get('/home', 'DashboardController@index')->name('home')->middleware('auth');

Route::get('/getGraphData', 'DashboardController@getGraphData')->name('getGraphData')->middleware('auth');
// User Controller
Route::resource('users', 'UserController')->middleware('auth');

// Machine Controller
Route::get('machines/all_machines', 'MachineController@autocomplete')->name('machine_autocomplete')->middleware('auth');
Route::get('machines/select_machine_num', 'MachineController@SelectMachineNum')->name('select_machine_num')->middleware('auth');
Route::get('/machines/search','MachineController@search')->name('machine_search')->middleware('auth');
Route::get('/machines/transfer_machine_autofill','MachineController@transferMachineAutofill')->name('transferMachineAutofill')->middleware('auth');
Route::get('/machines/duplicate_machine', 'MachineController@duplicateMachine')->name('duplicateMachine')->middleware('auth');
Route::resource('machines', 'MachineController')->middleware('auth');
// Route::get('/getGraphData', 'DashboardController@getGraphData')->name('getGraphData')->middleware('auth'); 
Route::get('/getCPAAdditionData', 'DashboardController@getCPAAdditionData')->name('getCPAAdditionData')->middleware('auth'); 
Route::get('/getBullhornSyncedData', 'DashboardController@getBullhornSyncedData')->name('getBullhornSyncedData')->middleware('auth'); 

Route::get('/getLogFilterData', 'DashboardController@getLogFilterData')->name('getLogFilterData')->middleware('auth'); 
// Technician Controller
Route::get('/technicians/autocomplete','TechnicianController@autocomplete')->name('technician_autocomplete')->middleware('auth');
Route::get('/technicians/search','TechnicianController@search')->name('technician_search')->middleware('auth');
Route::resource('technicians', 'TechnicianController')->middleware('auth');

// Log Controller
Route::get('/logs/get_history','LogController@get_history')->name('log_history')->middleware('auth');
Route::get('/logs/search','LogController@search')->name('log_search')->middleware('auth');
Route::resource('logs', 'LogController')->middleware('auth'); 
Route::get('/sources/searchwipe','ScriptController@searchwipe')->name('source_search_wipe')->middleware('auth');

// Source Controller
Route::get('/script/machine_source', 'ScriptController@machineSource')->name('machineSource')->middleware('auth');
Route::get('/script/autocomplete','ScriptController@autocomplete')->name('source_autocomplete')->middleware('auth');
Route::get('/script/autocompletewipe','ScriptController@autocompletewipe')->name('source_autocomplete_wipe')->middleware('auth');
Route::get('/script/search','ScriptController@search')->name('source_search')->middleware('auth');
Route::get('/script/search_source','ScriptController@search_source')->name('search_source')->middleware('auth');
Route::get('/script/pre_assign_source_search','ScriptController@preAssignSourceAutoComplete')->name('preAssignScriptearch')->middleware('auth');
Route::get('/script/transfer_source_auto_complete','ScriptController@transferSourceAutoComplete')->name('transferSourceAutoComplete')->middleware('auth');
Route::get('/script/pre_assign_source_auto_fill','ScriptController@preAssignSourceAutoFill')->name('preAssignSourceAutofill')->middleware('auth');
Route::get('/script/wipe_data_autofill','ScriptController@wipeDataAutoFill')->name('wipe_data_autofill')->middleware('auth');
Route::get('/script/logs','ScriptController@logs')->name('script.logs')->middleware('auth');
Route::get('/script/list','ScriptController@list')->name('script.list')->middleware('auth');
Route::resource('script', 'ScriptController')->middleware('auth');

Route::get('/contact/log_history/{id}','ContactController@getHistory')->middleware('auth')->name('contact.log_history');
Route::get('/contact/scriptrecord','ContactController@script_record')->name('contact.script_record')->middleware('auth');
Route::post('/contact/scriptrecord-paginate','ContactController@script_record_paginate')->name('contact.script_record_paginate')->middleware('auth');

// Route::get('/contact/scriptrecord-poplar','ContactController@getPoplarCampaigns')->name('contact.get_poplar_campaigns')->middleware('auth');
// Route::post('/contact/submit-scriptrecord-poplar','ContactController@sendPoplarPostcardCampaigns')->name('contact.submit_scriptrecord_poplar')->middleware('auth');

Route::group(['prefix' => 'poplar'], function(){
	Route::get('dump-poplar-campaign','PoplarController@dump_poplar_campaigns')->name('poplar.dump_poplar_campaigns'); //->middleware('auth');

	Route::get('scriptrecord-poplar','PoplarController@getPoplarCampaigns')->name('poplar.get_poplar_campaigns')->middleware('auth');
	Route::post('submit-scriptrecord-poplar','PoplarController@sendPoplarPostcardCampaigns')->name('poplar.submit_scriptrecord_poplar')->middleware('auth');

	/** Bullhorn IFrame Load */
	// Route::get('bullhorn/list-contact-campaigns/{bullhorn_id}','PoplarController@getListOfContactsByBullhornId')->name('poplar.bullhorn.list_contact_campaign');
	Route::get('bullhorn/list-contact-campaigns','PoplarController@getListOfContactsByBullhornId')->name('poplar.bullhorn.list_contact_campaign');
	Route::post('bullhorn/send-postcard-to-contact/{bullhorn_id}','PoplarController@sendPostcardToBUllhornContact')->name('poplar.bullhorn.send_postcard_contact');
});

Route::get('machines/log_history/{id}', 'MachineController@getHistory')->middleware('auth')->name('machine.log_history');
Route::get('/technicians/log_history/{id}','TechnicianController@getHistory')->middleware('auth')->name('technician.log_history');
Route::get('/script/log_history/{id}','ScriptController@getHistory')->middleware('auth');

Route::group(['prefix' => 'mailchimp'], function(){
	Route::get('listing/{page_number?}', 'MailchimpController@listing')->name('mailchimp.listing');
	Route::post('sync-data', 'MailchimpController@syncDataToBullhorn')->name('mailchimp.syncDataToBullhorn');
	Route::get('iframe-listing', 'MailchimpController@iframe_listing')->name('mailchimp.iframe_listing');
});

// Record Wipe Test Controller
Route::group(['middleware' => ['auth']], function () {
   	Route::get('/wipes/history','WipeController@history')->name('history');
   	Route::get('/wipes/wipes_search','WipeController@wipesSearch')->name('wipes_search');
	Route::get('/update-wipe','WipeController@updateWipe')->name('update-wipe');
	Route::get('/wipes/{id}/sendEmail','WipeController@sendEmail')->name('sendEmail');
	Route::get('/wipes/{id}/pdfView','WipeController@pdfView')->name('pdfView');
	Route::get('/wipes/discrepcod','WipeController@discrepcod')->name('discrepcod');
	Route::post('/wipes/storeMultiple','WipeController@storeMultiple')->name('wipes.storeMultiple');
	Route::get('/edit-RSO','WipeController@editRSO')->name('edit-RSO');
	Route::post('/update-RSO','WipeController@updateRSO')->name('update-RSO');
	Route::resource('wipes', 'WipeController');
});




// Pre-Assign Source Controller
Route::get('/preAssignSou/history','PreAssignScriptController@history')->name('prehistory')->middleware('auth');
Route::post('preAssignSou/createWipe', 'PreAssignScriptController@createWipe')->name('createWipe')->middleware('auth');
Route::post('preAssignSou/confirmShipDate', 'PreAssignScriptController@confirmShipDate')->name('confirmShipDate')->middleware('auth');
Route::get('/preAssignSou/search','PreAssignScriptController@search')->name('pre_assign_source_search')->middleware('auth');
Route::resource('preAssignSou', 'PreAssignScriptController')->middleware('auth');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Notifications\MailResetPasswordToken;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    protected $fillable = [
        'title', 'name', 'phone_no', 'email', 'password', 'role', 
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new MailResetPasswordToken($token));
    }

    public function role_name(){
        return $this->hasOne('App\Role','id','role');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use Auth;
use DB;

class UserController extends Controller
{
    public function index()
    {
        $users = User::orderBy('users.id', 'desc')
        ->paginate(env('page'));

        

        return view('user.index', compact('users'));
    }

    public function create()
    {
        $uroles = Role::all();

        return view('user.create', compact('uroles'));
    }

    public function store(Request $request)
    {
        $rules = [
            
            'name'     => 'required',
            'phone_no' => 'required|digits:10',
            'role'     => 'required',
            'email'    => 'required|email|unique:users,email',
            'password' => 'required',
        ];

        $message = [
            'name.required'     => 'User Name Field Is Required.',
            'phone_no.required' => 'User Phone Number Field Is Required.',
            'phone_no.digits'   => 'Please Enter Only 10 Digits.',
            'email.required'    => 'User Email Field Is Required.',
            'email.email'       => 'Please Enter Valid Email Address.',
            'email.unique'      => 'This Email All Ready In Used, Please Enter Another Email.',
            'role.required'     => 'Please Select User Role.',
            'email.password'    => 'User Password Field Is Required.',
        ];

        $this->validate($request, $rules, $message);

        $data = [
            'title'    => $request->title,
            'name'     => $request->name,
            'email'    => $request->email,
            'phone_no' => $request->phone_no,
            'role'     => $request->role,
            'password' => \Hash::make($request->password),
        ];

        $add_user = User::create($data);

        $user = auth()->user();
        activity()->performedOn($add_user)
                ->causedBy($user)
                ->withProperties(['name' => $user->name, 'email' => $user->email])
                ->log('Created user');

        return redirect()->route('users.index')->with('insert','Successfully Inserted User.');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $user = User::find($id);
        $uroles = Role::all();
        return view('user.edit', compact('user','uroles'));
    }

    public function update(Request $request, $id)
    {
       $rules = [
            
            'name'     => 'required',
            'phone_no' => 'required|digits:10',
            'email'    => 'required|email|unique:users,email,'.$id,
            'role'     => 'required',
        ];

        $message = [
            'name.required'     => 'User Name Field Is Required.',
            'phone_no.required' => 'User Phone Number Field Is Required.',
            'phone_no.digits'   => 'Please Enter Only 10 Digits.',
            'email.required'    => 'User Email Field Is Required.',
            'email.email'       => 'Please Enter Valid Email Address.',
            'email.unique'      => 'This Email All Ready In Used, Please Enter Another Email.',
            'email.password'    => 'User Password Field Is Required.',
            'role.required'     => 'Please Select User Role.',
            // 'phone_no.max' => 'Please Enter Only 10 Digits.',
        ];

        $this->validate($request, $rules, $message);

        $user = User::find($id);

        if(!empty($request->password))
        {
            $user->password = \Hash::make($request->password);
        }

        $user->title    = $request->title;
        $user->name     = $request->name;
        $user->email    = $request->email;
        $user->role     = $request->role;
        $user->phone_no = $request->phone_no;
        $user->status   = $request->status;
        $user->save();

        $users = auth()->user();
        activity()->performedOn($user)
                ->causedBy($users)
                ->withProperties(['name' => $user->name, 'email' => $user->email])
                ->log('Updated user');

        return redirect()->route('users.index')->with('update','Successfully Updated User.');
    }

    public function destroy($id)
    {
        $user = User::find($id)->delete();

        $users = auth()->user();
        activity()->performedOn($user)
                ->causedBy($users)
                ->withProperties(['name' => $user->name, 'email' => $user->email])
                ->log('Deleted user');

        return redirect()->route('users.index')->with('delete','Successfully Deleted User.');
    }

    public function changeUserStatus(Request $request)
    {
        $user = User::find($request->user_id);
        $user->status = $request->status;
        $user->save();
  
        return response()->json(['success'=>'User status change successfully.']);
    }
}

resources/views/user/create.blade.php
@extends('layout.app')

@section('content')
	<!-- Content -->
    <div class="content">
        <!-- Animated -->
        <div class="animated fadeIn">
        	<!--  Traffic  -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                        	<div class="row">
                        		<div class="col-lg-6">
                    				<h4 class="box-title">Add New User </h4>
                        		</div>
                        		<div class="col-lg-6">
                        			<a href="{{ route('users.index') }}" class="btn btn-outline-secondary float-right"><i class="fa fa-angle-double-left"></i> Back</a>
                        		</div>
                        	</div>
                        </div>
                        <div class="card-body">
                        	<form action="{{ route('users.store') }}" method="POST" enctype="multipart/form-data">
                                {{csrf_field()}}
                                <div class="row form-group">
	                              	<div class="col-md-6">
	                                	<label class="label_font_size" for="title">Enter Job Title :</label>
	                                	<input type="text" name="title" id="title" class="form-control input_size" value="{{ old('title') }}">
	                                	@if ($errors->has('title'))
	                                  		<div class="text-danger">{{ $errors->first('title') }}</div>
	                                	@endif
	                              	</div>
	                              	<div class="col-md-6">
	                                	<label class="label_font_size" for="name">Enter Name :</label>
	                                	<input type="text" name="name" id="name" class="form-control input_size" value="{{ old('name') }}">
	                                	@if ($errors->has('name'))
	                                  		<div class="text-danger">{{ $errors->first('name') }}</div>
	                                	@endif
	                              	</div>
	                            </div>

	                            <div class="row form-group">
	                              	<div class="col-md-6">
	                                	<label class="label_font_size" for="phone_no">Enter Phone Number :</label>
	                                	<input type="text" name="phone_no" id="phone_no" class="form-control input_size" value="{{ old('phone_no') }}">
	                                	@if ($errors->has('phone_no'))
	                                  		<div class="text-danger">{{ $errors->first('phone_no') }}</div>
	                                	@endif
	                              	</div>
	                              	<div class="col-md-6">
	                                	<label class="label_font_size" for="email">Enter Email :</label>
	                                	<input type="text" name="email" id="email" class="form-control input_size" value="{{ old('email') }}">
	                                	@if ($errors->has('email'))
	                                  		<div class="text-danger">{{ $errors->first('email') }}</div>
	                                	@endif
	                              	</div>
	                            </div>

	                            <div class="row form-group">
	                              	<div class="col-md-6">
			                            <label class="label_font_size" for="role">User Role :</label>
			                            <select class="form-control input_size" name="role" id="role" value="{{ old('role') }}">
			                                <option selected disabled>Select User Role</option>
			                                @foreach($uroles as $urole)
                                                <option value="{{ $urole->id }}">{{ $urole->name }}</option>
                                            @endforeach
			                            </select>
			                            @if ($errors->has('role'))
			                            	<div class="text-danger">{{ $errors->first('role') }}</div>
			                            @endif
			                        </div>
	                              	<div class="col-md-6">
	                                	<label class="label_font_size" for="password">Enter Password :</label>
	                                	<input type="password" name="password" id="password" class="form-control input_size" value="{{ old('password') }}">
	                                	@if ($errors->has('password'))
	                                  		<div class="text-danger">{{ $errors->first('password') }}</div>
	                                	@endif
	                              	</div>
	                            </div>
                            	
                            	<button type="submit" class="btn btn-outline-primary float-right"><i class="fa fa-save"></i> Save</button>
                        	</form>
				        </div><!-- card-body -->
                        <div class="card-body"></div>
                    </div>
                </div><!-- /# column -->
            </div>
            <!--  /Traffic -->
            <div class="clearfix"></div>
        </div>
    	<!-- .animated -->
    </div>
    <!-- /.content -->
    <div class="clearfix"></div>
@endsection

resources/views/user/index.blade.php
@extends('layout.app')

@section('content')

	<!-- Content -->
    <div class="content">
        <!-- Animated -->
        <div class="animated fadeIn">
        	<!--  Traffic  -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                        	<!-- Error & Message -->
	                        	@if (session()->has('insert'))
							      	<div class="alert alert-success alert-dismissible" role="alert">
							        	{{ session()->get('insert') }}
							        	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							          		<span aria-hidden="true">&times;</span>
							        	</button>
							      	</div>
							    @elseif (session()->has('update'))
							      	<div class="alert alert-info alert-dismissible" role="alert">
							        	{{ session()->get('update') }}
							        	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							          		<span aria-hidden="true">&times;</span>
							        	</button>
							      	</div>
							    @elseif (session()->has('delete'))
							      	<div class="alert alert-danger alert-dismissible" role="alert">
							        	{{ session()->get('delete') }}
							        	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							          		<span aria-hidden="true">&times;</span>
							        	</button>
							      	</div>
							    @endif
							<!-- Error & Message -->
                        	<div class="row">
                        		<div class="col-lg-6">
                    				<h4 class="box-title">User's List </h4>
                        		</div>
                        		<div class="col-lg-6">
                        			<a href="{{ route('users.create') }}" class="btn btn-outline-success float-right"><i class="fa fa-plus"></i> ADD</a>
                        		</div>
                        	</div>
                        </div>
                        <div class="card-body nopadding">
                        	<div class="col-md-12 table-stats order-table ov-h nopadding">
	                            <table class="table">
				                  	<thead>
					                    <tr>
					                    	<!-- <th>#</th> -->
					                      	<th>Job Title</th>
					                      	<th>Name</th>
					                      	<th>Email</th>
					                      	<th>Role</th>
					                      	<th>Phone Number</th>
					                      	<th>Status</th>
					                      	<th colspan="2" style="text-align: left;">Action</th>
					                    </tr>
				                  	</thead>

				                  	<tbody class="table_format">
				                    	<!-- {{$i = 1}}  -->
				                    	@forelse($users as $key => $user)
					                      	<tr>
						                        <!-- <td>{{ $users->firstItem() + $key }}</td> -->
						                        <td>{{ $user->title }}</td> 
						                        <td>{{ $user->name }}</td> 
						                        <td>{{ $user->email }}</td> 
						                        <td>{{ $user->role_name['name'] }}</td> 
						                        <td>{{ $user->phone_no }}</td>
						                        <td @if($user->status == 1)class="text-success" @else class="text-danger" @endif>{{ $user->status==1 ? 'Active' : 'Inactive' }}</td>
						                        <td>
						                        	<a href="{{ route('users.edit', $user) }}">
						                          		<i class="fa fa-edit edit_btn" rel="tooltip" title="Edit"></i>
						                          	</a>
						                        </td>
						                        <!-- <td>
						                        	<form action="{{ route('users.destroy', $user) }}" method="POST">
						                            	{{ csrf_field() }}
						                            	<input type="hidden" name="_method" value="DELETE">
						                            	<input type="hidden" name="_token" value="{{ csrf_token() }}">
						                            	<button type="submit" class="fabutton" onclick="return myFunction();">
						                            		<i class="fa fa-trash dlt_btn" rel="tooltip" title="Delete"></i>
						                            	</button>
						                          	</form>
						                        </td> -->
					                      	</tr>
				                    	@empty
					                        <tr>
					                          <td colspan="7" class="text-center">
					                          	<p>User Not Found.</p>
					                          </td> 
					                        </tr>
				                    	@endforelse
				                  	</tbody>
				                </table>
                        	</div> <!-- /.col-md-12 -->
				        </div><!-- card-body -->
                        <div class="card-body">
                            {{ $users->onEachSide(1)->links() }}
                        </div>
                        <div class="card-body"></div>
                    </div>
                </div><!-- /# column -->
            </div>
            <!--  /Traffic -->
            <div class="clearfix"></div>
        </div>
    	<!-- .animated -->
    </div>
    <!-- /.content -->
    <div class="clearfix"></div>
@endsection