routes/web.php
Route::post('/customer/create','CustomerController@store')->middleware('auth');
Route::get('/customer/search','CustomerController@search')->name('customer_search')->middleware('auth');
Route::get('/customer/autocomplete','CustomerController@autocomplete')->name('customer_autocomplete')->middleware('auth');
Route::get('/customer/view/{id}', 'CustomerController@view')->middleware('auth')->name('customer.view');
Route::get('/customer/main_search','CustomerController@main_search')->name('customer_main_search')->middleware('auth');
Route::get('/customer/state_autocomplete','CustomerController@state_autocomplete')->name('state_autocomplete')->middleware('auth');

Route::get('/customer/edit/{id}', 'CustomerController@edit')->name('customer_edit')->middleware('auth');
Route::post('/customer/update/{id}', 'CustomerController@update')->name('customer_update')->middleware('auth');
Route::post('/customer/delete/{id}', 'CustomerController@delete')->name('customer_delete')->middleware('auth');

Route::get('/customer/filter_machine_status','CustomerController@filterMachineStatus')->name('filterMachineStatus')->middleware('auth');


// Contact
Route::get('/contact', 'ContactController@index')->name('contact')->middleware('auth');
Route::get('/contact/create', 'ContactController@create')->middleware('auth');
Route::post('/contact/create','ContactController@store')->middleware('auth');

Route::get('/contact/edit/{id}', 'ContactController@edit')->name('contact_edit')->middleware('auth');
Route::post('/contact/update/{id}', 'ContactController@update')->name('contact_update')->middleware('auth');
Route::post('/contact/delete/{id}', 'ContactController@delete')->name('contact_delete')->middleware('auth');

Route::get('/contact/search','ContactController@search')->name('contact_search')->middleware('auth');




Route::get('/', 'Auth\LoginController@loginview')->middleware('auth');
Auth::routes();

Route::get('/home', 'DashboardController@index')->name('home')->middleware('auth');

Route::get('/getGraphData', 'DashboardController@getGraphData')->name('getGraphData')->middleware('auth');
// User Controller
Route::resource('users', 'UserController')->middleware('auth');

// Machine Controller
Route::get('machines/all_machines', 'MachineController@autocomplete')->name('machine_autocomplete')->middleware('auth');
Route::get('machines/select_machine_num', 'MachineController@SelectMachineNum')->name('select_machine_num')->middleware('auth');
Route::get('/machines/search','MachineController@search')->name('machine_search')->middleware('auth');
Route::get('/machines/transfer_machine_autofill','MachineController@transferMachineAutofill')->name('transferMachineAutofill')->middleware('auth');
Route::get('/machines/duplicate_machine', 'MachineController@duplicateMachine')->name('duplicateMachine')->middleware('auth');
Route::resource('machines', 'MachineController')->middleware('auth');
// Route::get('/getGraphData', 'DashboardController@getGraphData')->name('getGraphData')->middleware('auth'); 
Route::get('/getCPAAdditionData', 'DashboardController@getCPAAdditionData')->name('getCPAAdditionData')->middleware('auth'); 
Route::get('/getBullhornSyncedData', 'DashboardController@getBullhornSyncedData')->name('getBullhornSyncedData')->middleware('auth'); 

Route::get('/getLogFilterData', 'DashboardController@getLogFilterData')->name('getLogFilterData')->middleware('auth'); 
// Technician Controller
Route::get('/technicians/autocomplete','TechnicianController@autocomplete')->name('technician_autocomplete')->middleware('auth');
Route::get('/technicians/search','TechnicianController@search')->name('technician_search')->middleware('auth');
Route::resource('technicians', 'TechnicianController')->middleware('auth');

// Log Controller
Route::get('/logs/get_history','LogController@get_history')->name('log_history')->middleware('auth');
Route::get('/logs/search','LogController@search')->name('log_search')->middleware('auth');
Route::resource('logs', 'LogController')->middleware('auth'); 
Route::get('/sources/searchwipe','ScriptController@searchwipe')->name('source_search_wipe')->middleware('auth');

// Source Controller
Route::get('/script/machine_source', 'ScriptController@machineSource')->name('machineSource')->middleware('auth');
Route::get('/script/autocomplete','ScriptController@autocomplete')->name('source_autocomplete')->middleware('auth');
Route::get('/script/autocompletewipe','ScriptController@autocompletewipe')->name('source_autocomplete_wipe')->middleware('auth');
Route::get('/script/search','ScriptController@search')->name('source_search')->middleware('auth');
Route::get('/script/search_source','ScriptController@search_source')->name('search_source')->middleware('auth');
Route::get('/script/pre_assign_source_search','ScriptController@preAssignSourceAutoComplete')->name('preAssignScriptearch')->middleware('auth');
Route::get('/script/transfer_source_auto_complete','ScriptController@transferSourceAutoComplete')->name('transferSourceAutoComplete')->middleware('auth');
Route::get('/script/pre_assign_source_auto_fill','ScriptController@preAssignSourceAutoFill')->name('preAssignSourceAutofill')->middleware('auth');
Route::get('/script/wipe_data_autofill','ScriptController@wipeDataAutoFill')->name('wipe_data_autofill')->middleware('auth');
Route::get('/script/logs','ScriptController@logs')->name('script.logs')->middleware('auth');
Route::get('/script/list','ScriptController@list')->name('script.list')->middleware('auth');
Route::resource('script', 'ScriptController')->middleware('auth');

Route::get('/contact/log_history/{id}','ContactController@getHistory')->middleware('auth')->name('contact.log_history');
Route::get('/contact/scriptrecord','ContactController@script_record')->name('contact.script_record')->middleware('auth');
Route::post('/contact/scriptrecord-paginate','ContactController@script_record_paginate')->name('contact.script_record_paginate')->middleware('auth');

// Route::get('/contact/scriptrecord-poplar','ContactController@getPoplarCampaigns')->name('contact.get_poplar_campaigns')->middleware('auth');
// Route::post('/contact/submit-scriptrecord-poplar','ContactController@sendPoplarPostcardCampaigns')->name('contact.submit_scriptrecord_poplar')->middleware('auth');

Route::group(['prefix' => 'poplar'], function(){
	Route::get('dump-poplar-campaign','PoplarController@dump_poplar_campaigns')->name('poplar.dump_poplar_campaigns'); //->middleware('auth');

	Route::get('scriptrecord-poplar','PoplarController@getPoplarCampaigns')->name('poplar.get_poplar_campaigns')->middleware('auth');
	Route::post('submit-scriptrecord-poplar','PoplarController@sendPoplarPostcardCampaigns')->name('poplar.submit_scriptrecord_poplar')->middleware('auth');

	/** Bullhorn IFrame Load */
	// Route::get('bullhorn/list-contact-campaigns/{bullhorn_id}','PoplarController@getListOfContactsByBullhornId')->name('poplar.bullhorn.list_contact_campaign');
	Route::get('bullhorn/list-contact-campaigns','PoplarController@getListOfContactsByBullhornId')->name('poplar.bullhorn.list_contact_campaign');
	Route::post('bullhorn/send-postcard-to-contact/{bullhorn_id}','PoplarController@sendPostcardToBUllhornContact')->name('poplar.bullhorn.send_postcard_contact');
});

Route::get('machines/log_history/{id}', 'MachineController@getHistory')->middleware('auth')->name('machine.log_history');
Route::get('/technicians/log_history/{id}','TechnicianController@getHistory')->middleware('auth')->name('technician.log_history');
Route::get('/script/log_history/{id}','ScriptController@getHistory')->middleware('auth');

Route::group(['prefix' => 'mailchimp'], function(){
	Route::get('listing/{page_number?}', 'MailchimpController@listing')->name('mailchimp.listing');
	Route::post('sync-data', 'MailchimpController@syncDataToBullhorn')->name('mailchimp.syncDataToBullhorn');
	Route::get('iframe-listing', 'MailchimpController@iframe_listing')->name('mailchimp.iframe_listing');
});

// Record Wipe Test Controller
Route::group(['middleware' => ['auth']], function () {
   	Route::get('/wipes/history','WipeController@history')->name('history');
   	Route::get('/wipes/wipes_search','WipeController@wipesSearch')->name('wipes_search');
	Route::get('/update-wipe','WipeController@updateWipe')->name('update-wipe');
	Route::get('/wipes/{id}/sendEmail','WipeController@sendEmail')->name('sendEmail');
	Route::get('/wipes/{id}/pdfView','WipeController@pdfView')->name('pdfView');
	Route::get('/wipes/discrepcod','WipeController@discrepcod')->name('discrepcod');
	Route::post('/wipes/storeMultiple','WipeController@storeMultiple')->name('wipes.storeMultiple');
	Route::get('/edit-RSO','WipeController@editRSO')->name('edit-RSO');
	Route::post('/update-RSO','WipeController@updateRSO')->name('update-RSO');
	Route::resource('wipes', 'WipeController');
});




// Pre-Assign Source Controller
Route::get('/preAssignSou/history','PreAssignScriptController@history')->name('prehistory')->middleware('auth');
Route::post('preAssignSou/createWipe', 'PreAssignScriptController@createWipe')->name('createWipe')->middleware('auth');
Route::post('preAssignSou/confirmShipDate', 'PreAssignScriptController@confirmShipDate')->name('confirmShipDate')->middleware('auth');
Route::get('/preAssignSou/search','PreAssignScriptController@search')->name('pre_assign_source_search')->middleware('auth');
Route::resource('preAssignSou', 'PreAssignScriptController')->middleware('auth');

Route::get('update-source-log', 'PreAssignScriptController@updateSourceLog')->name('update-source-log')->middleware('auth');

// Transfer Source Controller
Route::resource('TransferSou', 'TransferScriptController')->middleware('auth');
Route::get('TransferSou/confirm/{id}', 'TransferScriptController@confirm')->name('TransferSou.confirm')->middleware('auth');
Route::post('update_confirmlog', 'TransferScriptController@updateconfirmlog')->name('update_confirmlog')->middleware('auth');
// Signature Upload Controller

app/Technician.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Technician extends Model 
{
    use SoftDeletes;

    protected $table = 'technicians';
    protected $fillable = [
        'tech_name', 't_firstname', 't_lastname', 'current','type'
    ];

public function tech_type(){
        return $this->hasOne('App\TechnicianType','id','type');
    }
}

app/TechnicianType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class TechnicianType extends Model 
{

    protected $table = 'technician_type';
    protected $fillable = [
        'technician_type'
    ];
}

resources/views/technician/create.blade.php
@extends('layout.app')

@section('content')
	<!-- Content -->
    <div class="content">
        <!-- Animated -->
        <div class="animated fadeIn">
        	<!--  Traffic  -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                        	<div class="row">
                        		<div class="col-lg-6">
                    				<h4 class="box-title">Add New Technician </h4>
                        		</div>
                        		<div class="col-lg-6">
                        			<a href="{{ route('technicians.index') }}" class="btn btn-outline-secondary float-right"><i class="fa fa-angle-double-left"></i> Back</a>
                        		</div>
                        	</div>
                        </div>
                        <div class="card-body">
                        	<form action="{{ route('technicians.store') }}" method="POST" enctype="multipart/form-data">
                                {{csrf_field()}}
                                <div class="row form-group">
                                  	<div class="col-md-6">
                                    	<label class="label_font_size" for="tech_name">Enter Technician Name :</label>
                                    	<input type="text" name="tech_name" id="tech_name" class="form-control input_size" value="{{ old('tech_name') }}" placeholder="eg. MSCH">
                                    	@if ($errors->has('tech_name'))
                                      		<div class="text-danger">{{ $errors->first('tech_name') }}</div>
                                    	@endif
                                  	</div>
                                  	<div class="col-md-6">
                                    	<label class="label_font_size" for="t_firstname">Enter Technician First Name :</label>
                                    	<input type="text" name="t_firstname" id="t_firstname" class="form-control input_size" value="{{ old('t_firstname') }}" placeholder="eg. Michael">
                                    	@if ($errors->has('t_firstname'))
                                      		<div class="text-danger">{{ $errors->first('t_firstname') }}</div>
                                    	@endif
                                  	</div>
                                </div>
                                <div class="row form-group">
                                  	<div class="col-md-6">
                                    	<label class="label_font_size" for="t_lastname">Enter Technician Last Name :</label>
                                    	<input type="text" name="t_lastname" id="t_lastname" class="form-control input_size" value="{{ old('t_lastname') }}" placeholder="eg. Bernard">
                                    	@if ($errors->has('t_lastname'))
                                      		<div class="text-danger">{{ $errors->first('t_lastname') }}</div>
                                    	@endif
                                  	</div>
                                  	<div class="col-md-6">
			                            <label class="label_font_size" for="current">Select Technician Status:</label>
			                            <select class="form-control input_size" name="current" id="current" value="{{ old('current') }}">
			                                <option selected disabled>Select Technician Status</option>
			                                <option value="0">Active</option>
			                                <option value="1">Deactve</option>
			                            </select>
			                            @if ($errors->has('current'))
			                            	<div class="text-danger">{{ $errors->first('current') }}</div>
			                            @endif
			                        </div>
			                    </div>
                                <div class="row form-group">
                                    <div class="col-md-6">
                                        <label class="label_font_size" for="role">Technician Type :</label>
                                        <select class="form-control input_size" name="type" id="role" value="{{ old('type') }}">
                                            <option selected disabled>Select Technician Type</option>
                                            @foreach($uroles as $urole)
                                                <option value="{{ $urole->id }}">{{ $urole->technician_type }}</option>
                                            @endforeach
                                        </select>
                                        @if ($errors->has('type'))
                                            <div class="text-danger">{{ $errors->first('type') }}</div>
                                        @endif
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-outline-primary float-right"><i class="fa fa-save"></i> Save</button>
                        	</form>
                        </div>
                        <div class="card-body"></div>
                    </div>
                </div><!-- /# column -->
            </div>
            <!--  /Traffic -->
            <div class="clearfix"></div>
        </div>
    	<!-- .animated -->
    </div>
    <!-- /.content -->
    <div class="clearfix"></div>
@endsection

resources/views/technician/edit.blade.php
@extends('layout.app')

@section('content')
	<!-- Content -->
    <div class="content">
        <!-- Animated -->
        <div class="animated fadeIn">
        	<!--  Traffic  -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                        	<div class="row">
                        		<div class="col-lg-6">
                    				<h4 class="box-title">Edit Technician </h4>
                        		</div>
                        		<div class="col-lg-6">
                        			<a href="{{ route('technicians.index') }}" class="btn btn-outline-secondary float-right"><i class="fa fa-angle-double-left"></i> Back</a>
                        		</div>
                        	</div>
                        </div>
                        <div class="card-body">
                        	<form action="{{ route('technicians.update', $technician) }}" method="POST" enctype="multipart/form-data">
                                {{csrf_field()}}
                                <input type="hidden" name="_method" value="PUT">
                              	<div class="row form-group">
                                  	<div class="col-md-6">
                                    	<label class="label_font_size" for="tech_name">Enter Technician Name :</label>
                                    	<input type="text" name="tech_name" id="tech_name" class="form-control input_size" value="{{ $technician->tech_name }}">
                                    	@if ($errors->has('tech_name'))
                                      		<div class="text-danger">{{ $errors->first('tech_name') }}</div>
                                    	@endif
                                  	</div>
                                  	<div class="col-md-6">
                                    	<label class="label_font_size" for="t_firstname">Enter Technician First Name :</label>
                                    	<input type="text" name="t_firstname" id="t_firstname" class="form-control input_size" value="{{ $technician->t_firstname }}">
                                    	@if ($errors->has('t_firstname'))
                                      		<div class="text-danger">{{ $errors->first('t_firstname') }}</div>
                                    	@endif
                                  	</div>
                                </div>

                                <div class="row form-group">
                                  	<div class="col-md-6">
                                    	<label class="label_font_size" for="t_lastname">Enter Technician Last Name :</label>
                                    	<input type="text" name="t_lastname" id="t_lastname" class="form-control input_size" value="{{ $technician->t_lastname }}">
                                    	@if ($errors->has('t_lastname'))
                                      		<div class="text-danger">{{ $errors->first('t_lastname') }}</div>
                                    	@endif
                                  	</div>
                                  	<div class="col-md-6">
			                            <label class="label_font_size" for="current">Select Technician Status :</label>
			                            <select class="form-control input_size" name="current" id="current" value="{{ $technician->current }}">
			                                <option selected disabled>Select Technician Status</option>
			                                <option value="0" {{ $technician->current == '0' ? 'selected' : ''}} >Active</option>
			                                <option value="1" {{ $technician->current == '1' ? 'selected' : ''}} >Inactive</option>
			                            </select>
			                            @if ($errors->has('current'))
			                            	<div class="text-danger">{{ $errors->first('current') }}</div>
			                            @endif
			                        </div>
                              	</div>
                                <div class="row form-group">
                                    <div class="col-md-6">
                                        <label class="label_font_size" for="role">Technician Type :</label>
                                        <select class="form-control input_size" name="type" id="role" value="{{ old('type') }}">
                                            <option selected disabled>Select Technician Type</option>
                                            @foreach($uroles as $urole)
                                            <option value="{{ $urole->id }}" {{ $technician->type == $urole->id ? 'selected' : ''}}>{{ $urole->technician_type }}</option>
                                            @endforeach
                                        </select>
                                        @if ($errors->has('type'))
                                            <div class="text-danger">{{ $errors->first('type') }}</div>
                                        @endif
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-outline-primary float-right"><i class="fa fa-save"></i> Update</button>
                        	</form>
                        </div>
                        <div class="card-body"></div>
                    </div>
                </div><!-- /# column -->
            </div>
            <!--  /Traffic -->
            <div class="clearfix"></div>
        </div>
    	<!-- .animated -->
    </div>
    <!-- /.content -->
    <div class="clearfix"></div>
@endsection

resources/views/technician/index.blade.php
@extends('layout.app')

@section('content')

	<!-- Content -->
    <div class="content">
        <!-- Animated -->
        <div class="animated fadeIn">
        	<!--  Traffic  -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                        	<!-- Error & Message -->
	                        	@if (session()->has('insert'))
							      	<div class="alert alert-success alert-dismissible" role="alert">
							        	{{ session()->get('insert') }}
							        	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							          		<span aria-hidden="true">&times;</span>
							        	</button>
							      	</div>
							    @elseif (session()->has('update'))
							      	<div class="alert alert-info alert-dismissible" role="alert">
							        	{{ session()->get('update') }}
							        	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							          		<span aria-hidden="true">&times;</span>
							        	</button>
							      	</div>
							    @elseif (session()->has('delete'))
							      	<div class="alert alert-danger alert-dismissible" role="alert">
							        	{{ session()->get('delete') }}
							        	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							          		<span aria-hidden="true">&times;</span>
							        	</button>
							      	</div>
							    @endif
							<!-- Error & Message -->
                        	<div class="row form-group">
                        		<div class="col-md-9">
                    				<h4 class="box-title">Technician List </h4>
                        		</div>

                        		<div class="col-md-3">
                        			<a href="{{ route('technicians.create') }}" class="btn btn-outline-success float-right"><i class="fa fa-plus"></i> ADD</a>
                        		</div>
                        	</div>

                        	<div class="row form-group">

                        		<div class="col-md-6">
                        			<div class="input-group">
                        				<input class="form-control"  name="search_term" id="search_tech_term" placeholder="Search Technician Name, First Name, Last Name">
                        				
                        			</div>
                        		</div>

	                        	<div class="col-md-3">
						            <div class="input-group">
						                <select class="form-control" name="status" id="status">
						                    <option selected disabled>Select Status</option>
						                    <option value="0">Active</option>
						                    <option value="1">Inactive</option>
						                </select>
						            </div>
						        </div>
						        <div class="col-md-3">	
						        			<div class="input-group-btn">
	                        					<button type="button" id="search_technician" class="btn btn-outline-primary" >Search</button>
	                        				

	                        				<a class="btn input-group-btn"href="{{ route('technicians.index') }}" >Reset</a></div>
	                        	</div>			
                        	</div>	

                        </div>
                        <div class="card-body nopadding">
                        	<div id="searchid" class="col-md-12 table-stats order-table ov-h nopadding">
	                            <table class="table">
				                  	<thead>
					                    <tr>
					                    	<!-- <th>#</th> -->
					                      	<th>Technician name</th>
					                      	<th>First Name</th>
					                      	<th>Last Name</th>
					                      	<th>Current Status</th>
					                      	<th>Type</th>
					                      	<th>Updated At</th>
					                      	<th colspan="2" style="text-align: center;">Action</th>
					                    </tr>
				                  	</thead>

				                  	<tbody class="table_format">
				                    	<!-- {{$i = 1}}  -->
				                    	@forelse($technicians as $key => $technician)
					                      	<tr>
						                        <!-- <td>{{ $technicians->firstItem() + $key }}</td>  -->
						                        <!-- <td>{{ $technician->tech_name }}</td>  -->
												<td>
                                                    <a class=""  rel="tooltip" title="View" href="{{ url('technicians/log_history',$technician->id) }}">
                                                    <u>{{$technician->tech_name}}</u>
                                                    </a>
                                                </td>
						                        <td>{{ $technician->t_firstname }}</td> 
						                        <td>{{ $technician->t_lastname }}</td> 
						                        <td @if($technician->current == 0)class="text-success" @else class="text-danger" @endif>{{ $technician->current == 0 ? 'Active' : 'Inactive' }}</td> 
						                        <td>{{ $technician->tech_type['technician_type'] }}</td> 
						                        <td>{{ !empty($technician->updated_at)?date('d M Y', strtotime($technician->updated_at)):'-' }}</td>
						                        <td style="text-align: right;">
						                          <a href="{{ route('technicians.edit', $technician) }}">
						                          	<i class="fa fa-edit edit_btn technician_edit_btn" rel="tooltip" title="Edit"></i>
						                          </a>
						                        </td>
						                        <!-- <td style="padding-left: 0px; text-align: left;">
						                        	<form action="{{ route('technicians.destroy', $technician) }}" method="POST">
						                            {{ csrf_field() }}
						                            	<input type="hidden" name="_method" value="DELETE">
						                            	<input type="hidden" name="_token" value="{{ csrf_token() }}">
						                            	<button type="submit" class="fabutton" onclick="return myFunction();">
						                              		<i class="fa fa-trash dlt_btn" rel="tooltip" title="Delete"></i>
						                            	</button>
						                          	</form>
						                        </td> -->
					                      	</tr>
				                    	@empty
					                        <tr>
					                          <td colspan="6" class="text-center">
					                          	<p>Technician Not Found.</p>
					                          </td> 
					                        </tr>
				                    	@endforelse
				                  	</tbody>
				                </table>
                        	</div> <!-- col-md-12 -->
				        </div><!-- card-body -->
                        <div class="card-body page_hide">
                            {{ $technicians->onEachSide(1)->links() }}
                        </div>
                        <div class="card-body"></div>
                    </div>
                </div><!-- /# column -->
            </div>
            <!--  /Traffic -->
            <div class="clearfix"></div>
        </div>
    	<!-- .animated -->
    </div>
    <!-- /.content -->
    <div class="clearfix"></div>


 <!-- Search Technician -->
        <script>
            jQuery(document).ready(function(){
                function fetch_technician_data(query,status,page)
                {
                    jQuery.ajax({
                        url:"{{ route('technician_search') }}",
                        method:'GET',
                        data:{query:query,status:status,page:page},
                        dataType:'html',
                        success:function(data)
                        {
                            jQuery('#searchid').html(data);
                            jQuery('.page_hide').css('cssText', 'display:none');
                        }
                    })
                }

                jQuery(document).on('click', '#search_technician', function(){
                    var query = jQuery('#search_tech_term').val();
                    var status = jQuery('#status').val();

                    if (query != '' || null !=status) {
                        fetch_technician_data(query,status,1);

                    }
                });

                jQuery(document).on('click', '.pagination a', function(event){
	                  

	                  var query = jQuery('#search_tech_term').val();
	                  var status = jQuery('#status').val();
	                     if (query != ''  || null !=status) {
	                     	event.preventDefault(); 
	                  var page = jQuery(this).attr('href').split('page=')[1];
	                  
	                     fetch_technician_data(query,status,page);

	                   }  
	                 });
                
            });

            jQuery('#search_tech_term').keypress(function (e) {
                var key = e.which;
                if(key == 13)  // the enter key code
                {
                    jQuery('#search_technician').click();
                    return false;  
                }
            });  
        </script>
    <!-- Search Technician -->

@endsection